Repository equinor/isar, pull requests merged in 2021-11, with the labels that each got.

#3 Replace flask with fastAPI
  .flaskenv
  .gitignore
  README.md
  main.py
  setup.py
  src/isar/__init__.py
  src/isar/apis/__init__.py
  src/isar/apis/missions/__init__.py
  src/isar/apis/missions/list_predefined_missions.py
  src/isar/apis/schedule/drive_to.py
  src/isar/apis/schedule/image_towards_coordinate.py
  src/isar/apis/schedule/router.py
  src/isar/apis/schedule/start_mission.py
  src/isar/apis/schedule/stop_mission.py
  src/isar/apis/telemetry/__init__.py
  src/isar/apis/telemetry/mission_status.py
  src/isar/app.py
  src/isar/config/config.py
  src/isar/config/default.ini
  src/isar/config/log.py
  src/isar/config/logging.conf
  src/isar/modules.py
  src/isar/services/readers/base_reader.py
  src/isar/services/readers/map_reader.py
  src/isar/services/service_connections/stid/stid_service.py
  src/isar/services/utilities/json_service.py
  src/isar/state_machine/states/idle.py
  tests/api/apis/schedule/__init__.py
  tests/api/apis/schedule/test_start_mission.py
  tests/api/apis/supervisor/test_supervisor_routes.py
  tests/api/services/readers/test_map_reader.py
  tests/conftest.py
  tests/test_utilities/mock_interface/mock_robot_interface.py
Labels: enhancement

#102 Make STID service independent of plant
  src/isar/config/default.ini
  src/isar/services/service_connections/stid/stid_service.py
Labels: bug

#104 Restructure configuration
  README.md
  main.py
  src/isar/apis/api.py
  src/isar/apis/schedule/stop_mission.py
  src/isar/apis/security/authentication.py
  src/isar/config/config.py
  src/isar/config/default.ini
  src/isar/config/predefined_missions/__init__.py
  src/isar/config/predefined_missions/klab_mission.json
  src/isar/config/predefined_missions/mission_1.json
  src/isar/config/predefined_missions/mission_2.json
  src/isar/config/predefined_missions/mission_3.json
  src/isar/config/predefined_missions/mission_4.json
  src/isar/config/predefined_missions/mission_5.json
  src/isar/config/predefined_missions/mission_7.json
  src/isar/mission_planner/echo_planner.py
  src/isar/mission_planner/local_planner.py
  src/isar/models/mission.py
  src/isar/models/mission_metadata/recommended_metadata.py
  src/isar/modules.py
  src/isar/services/readers/map_reader.py
  src/isar/services/service_connections/request_handler.py
  src/isar/services/service_connections/stid/stid_service.py
  src/isar/services/utilities/scheduling_utilities.py
  src/isar/state_machine/state_machine.py
  src/isar/storage/blob_storage.py
  src/isar/storage/local_storage.py
  src/isar/storage/storage_service.py
  tests/isar/services/readers/test_mission_reader.py
Labels: documentation, enhancement

#108 Remove redundant missions to only support default
  src/isar/config/predefined_missions/default.json
  src/isar/config/predefined_missions/klab_mission.json
  src/isar/config/predefined_missions/mission_1.json
  src/isar/config/predefined_missions/mission_3.json
  src/isar/config/predefined_missions/mission_4.json
  src/isar/config/predefined_missions/mission_5.json
  src/isar/config/predefined_missions/mission_7.json
  tests/isar/services/readers/test_mission_reader.py
Labels: refactor

#126 Set release 1.2.0
  setup.py
Labels: release
