Repository equinor/isar, pull requests merged in 2021-10, with the labels that each got.

#46 Add missing StorageModule to injector
  src/isar/__init__.py
  src/isar/storage/storage_interface.py
Labels: bug

#59 Local storage implementation
  src/isar/config/default.ini
  src/isar/modules.py
  src/isar/storage/local_storage.py
Labels: enhancement

#62 Add instructions for changing storage to readme
  README.md
Labels: documentation
