Repository equinor/isar, pull requests merged in 2022-10, with the labels that each got.

#339 Update SLIMM endpoint variables
  src/isar/config/settings.py
  src/isar/storage/slimm_storage.py
Labels: bug

#340 Set log levels for azure and main loggers
  src/isar/config/logging.conf
  src/isar/config/settings.py
Labels: improvement

#346 Add default robot package installation to dockerfile
  Dockerfile
Labels: bug

#350 Add role based access control to all endpoints
  src/isar/apis/security/authentication.py
  src/isar/config/settings.py
Labels: feature

#352 Add mission inspection types to uploader
  src/isar/storage/utilities.py
Labels: bug

#353 Add responses to pause, resume, stop mission endpoints
  src/isar/apis/models/models.py
  src/isar/apis/schedule/scheduling_controller.py
  src/isar/services/utilities/scheduling_utilities.py
  src/isar/state_machine/state_machine.py
Labels: improvement

#354 Get retry attempts for stop from settings
  src/isar/config/settings.py
  src/isar/state_machine/states/stop_step.py
Labels: improvement

#355 Change sleep time from int to float
  src/isar/config/settings.py
Labels: bug
