Repository equinor/isar, pull requests merged in 2023-03, with the labels that each got.

#419 Handle communication exception in robot status
  src/isar/services/service_connections/mqtt/robot_status_publisher.py
Labels: bug

#425 Revert change to metadata type
  src/isar/config/settings.py
  src/robot_interface/models/inspection/inspection.py
Labels: bug

#427 Remove 'OPENAPI_CLIENT_ID'
  src/isar/apis/api.py
  src/isar/apis/security/authentication.py
  src/isar/config/settings.py
Labels: bug, improvement

#401 Universally unique identifier on Isar
  main.py
  src/isar/apis/models/models.py
  src/isar/apis/schedule/scheduling_controller.py
  src/isar/config/settings.env
  src/isar/config/settings.py
  src/isar/models/mission/mission.py
  src/isar/models/mission_metadata/mission_metadata.py
  src/isar/modules.py
  src/isar/services/service_connections/mqtt/robot_info_publisher.py
  src/isar/services/service_connections/mqtt/robot_status_publisher.py
  src/isar/state_machine/state_machine.py
  src/isar/storage/slimm_storage.py
  src/isar/storage/utilities.py
  src/robot_interface/robot_interface.py
  src/robot_interface/telemetry/mqtt_client.py
  src/robot_interface/telemetry/payloads.py
  tests/mocks/robot_interface.py
Labels: breaking-change, improvement

#432 Add pressure payload
  src/robot_interface/telemetry/payloads.py
Labels: improvement

#433 Add RecordAudio inspection step
  src/isar/apis/models/start_mission_definition.py
  src/robot_interface/models/inspection/__init__.py
  src/robot_interface/models/inspection/inspection.py
  src/robot_interface/models/mission/step.py
Labels: feature

#423 Move mission to robot interface
  src/isar/apis/models/start_mission_definition.py
  src/isar/apis/schedule/scheduling_controller.py
  src/isar/mission_planner/echo_planner.py
  src/isar/mission_planner/local_planner.py
  src/isar/mission_planner/mission_planner_interface.py
  src/isar/mission_planner/sequential_task_selector.py
  src/isar/mission_planner/task_selector_interface.py
  src/isar/models/communication/message.py
  src/isar/models/mission/__init__.py
  src/isar/models/mission/status.py
  src/isar/models/mission_metadata/mission_metadata.py
  src/isar/services/service_connections/mqtt/robot_status_publisher.py
  src/isar/services/utilities/scheduling_utilities.py
  src/isar/state_machine/state_machine.py
  src/isar/state_machine/states/idle.py
  src/isar/state_machine/states/monitor.py
  src/isar/storage/slimm_storage.py
  src/isar/storage/utilities.py
  src/robot_interface/models/inspection/inspection.py
  src/robot_interface/models/mission/__init__.py
  src/robot_interface/models/mission/mission.py
  src/robot_interface/models/mission/status.py
  src/robot_interface/models/mission/step.py
  src/robot_interface/models/mission/task.py
  src/robot_interface/robot_interface.py
  src/robot_interface/utilities/uuid_string_factory.py
  tests/integration/turtlebot/test_successful_mission.py
  tests/isar/models/test_start_mission_definition.py
  tests/isar/services/readers/test_base_reader.py
  tests/isar/services/readers/test_mission_reader.py
  tests/isar/services/service_connections/echo/test_echo_service.py
  tests/isar/state_machine/states/test_monitor.py
  tests/isar/state_machine/test_state_machine.py
  tests/isar/storage/test_blob_storage.py
  tests/isar/storage/test_uploader.py
  tests/mocks/mission_definition.py
  tests/mocks/robot_interface.py
  tests/mocks/step.py
Labels: breaking-change

#450 Remove echo planner
  README.md
  docker-compose-turtlebot.yml
  docker-compose.yml
  src/isar/config/settings.env
  src/isar/config/settings.py
  src/isar/mission_planner/echo_planner.py
  src/isar/modules.py
  tests/conftest.py
  tests/isar/services/service_connections/echo/test_echo_service.py
Labels: improvement
