Repository equinor/isar, pull requests merged in 2024-12, with the labels that each got.

#667 Move MediaConfig to prevent circular dependencies
  src/isar/apis/models/media_connection_type.py
  src/isar/apis/models/models.py
  src/isar/services/utilities/robot_utilities.py
  src/robot_interface/models/robots/media.py
  src/robot_interface/robot_interface.py
  tests/mocks/robot_interface.py
Labels: breaking-change, improvement

#666 Pass on task zoom value from API
  src/isar/apis/models/start_mission_definition.py
  src/robot_interface/models/mission/task.py
Labels: improvement

#681 Use payloads for mqtt messages
  src/isar/state_machine/state_machine.py
  src/isar/storage/uploader.py
  src/robot_interface/telemetry/payloads.py
Labels: refactor
