Repository equinor/isar, pull requests merged in 2025-09, with the labels that each got.

#900 Improve mqtt messages
  src/isar/config/settings.py
  src/isar/services/service_connections/mqtt/mqtt_client.py
  src/isar/services/service_connections/mqtt/robot_heartbeat_publisher.py
  src/isar/state_machine/state_machine.py
  src/robot_interface/telemetry/mqtt_client.py
Labels: bug, feature

#907 Do not publish messages on empty BlobStoragePath
  src/isar/storage/uploader.py
  tests/isar/storage/test_uploader.py
  tests/test_double/blob_storage.py
  tests/test_double/mqtt_client.py
Labels: bug

#922 Add RobotUnreliableDockingStatusException
  src/robot_interface/models/exceptions/robot_exceptions.py
Labels: improvement
