Repository equinor/isar, pull requests merged in 2025-05, with the labels that each got.

#785 Fix crashing if inspection_description is None
  src/isar/storage/utilities.py
Labels: bug

#788 Remove initiate_task function
  src/robot_interface/robot_interface.py
Labels: good first issue, improvement

#789 Add support for CO2 gas measurements
  src/isar/apis/models/start_mission_definition.py
  src/isar/config/settings.py
  src/isar/storage/uploader.py
  src/robot_interface/models/inspection/inspection.py
  src/robot_interface/models/mission/task.py
  src/robot_interface/telemetry/payloads.py
  tests/isar/storage/test_uploader.py
Labels: feature
